import { createClient } from "npm:@supabase/supabase-js@2";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,"Content-Type":"application/json"}});
const normalize=(v:string)=>String(v||"").trim().toLowerCase().replace(/[^a-z0-9]/g,"");
const authEmail=(role:string,id:string)=>String(id).includes("@")?String(id).trim().toLowerCase():`${({teacher:"t",student:"s",parent:"p",admin:"u"} as Record<string,string>)[role]||"u"}.${normalize(id)}@learnersguide.in`;
async function findUser(a:ReturnType<typeof createClient>,email:string){const{data,error}=await a.auth.admin.listUsers({page:1,perPage:1000});if(error)throw error;return data.users.find(u=>(u.email||"").toLowerCase()===email.toLowerCase())||null;}
async function getUser(a:ReturnType<typeof createClient>,id:string|null){if(!id)return null;const{data,error}=await a.auth.admin.getUserById(id);if(error){if(error.status===404||error.code==="user_not_found")return null;throw error;}return data.user||null;}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});try{const h=req.headers.get("Authorization");if(!h)return json({error:"Missing authorization"},401);const url=Deno.env.get("SUPABASE_URL")||"",anon=Deno.env.get("SUPABASE_ANON_KEY")||"",service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";if(!url||!anon||!service)return json({error:"Supabase environment is not configured"},500);const token=h.replace(/^Bearer\s+/i,"");const caller=createClient(url,anon);const{data:cd,error:ce}=await caller.auth.getUser(token);if(ce||!cd.user)return json({error:`Invalid authorization${ce?.message?`: ${ce.message}`:""}`},401);const admin=createClient(url,service);const{data:sc,error:se}=await admin.auth.admin.getUserById(cd.user.id);if(se)return json({error:`Unable to verify administrator: ${se.message}`},500);if(sc.user?.app_metadata?.role!=="admin")return json({error:"Administrator access required",role:sc.user?.app_metadata?.role??null},403);const b=await req.json();const action=String(b.action||""),role=String(b.role||""),loginId=String(b.loginId||""),password=String(b.password||""),name=String(b.name||"User"),ref=b.ref?String(b.ref):null,authId=b.authId?String(b.authId):null;if(!["student","parent","teacher"].includes(role))return json({error:"Invalid role"},400);if(!loginId)return json({error:"loginId is required"},400);const email=authEmail(role,loginId),existing=await findUser(admin,email);
if(action==="create"){if(!password)return json({error:"Password is required"},400);if(existing){const{data,error}=await admin.auth.admin.updateUserById(existing.id,{password,user_metadata:{...(existing.user_metadata||{}),name,phone:loginId},app_metadata:{...(existing.app_metadata||{}),role,ref}});if(error)throw error;return json({authId:data.user.id,email:data.user.email,updated:true});}const{data,error}=await admin.auth.admin.createUser({email,password,email_confirm:true,user_metadata:{name,phone:loginId},app_metadata:{role,ref}});if(error)throw error;return json({authId:data.user.id,email:data.user.email,created:true});}
if(action==="update"){let u=await getUser(admin,authId);if(!u)u=existing;if(!u){if(!password)return json({error:"Authentication account not found. A password is required to recreate it.",code:"AUTH_ACCOUNT_MISSING"},404);const{data,error}=await admin.auth.admin.createUser({email,password,email_confirm:true,user_metadata:{name,phone:loginId},app_metadata:{role,ref}});if(error)throw error;return json({authId:data.user.id,email:data.user.email,created:true,repaired:true});}const patch:Record<string,unknown>={user_metadata:{...(u.user_metadata||{}),name,phone:loginId},app_metadata:{...(u.app_metadata||{}),role,ref}};if(password)patch.password=password;if(u.email?.toLowerCase()!==email.toLowerCase()){patch.email=email;patch.email_confirm=true;}const{data,error}=await admin.auth.admin.updateUserById(u.id,patch);if(error)throw error;return json({authId:data.user.id,email:data.user.email,updated:true,repaired:authId!==data.user.id});}
if(action==="delete"){if(!authId)return json({deleted:false,reason:"No authId supplied"});const u=await getUser(admin,authId);if(!u)return json({authId,deleted:true,alreadyMissing:true});const{error}=await admin.auth.admin.deleteUser(authId);if(error)throw error;return json({authId,deleted:true});}return json({error:"Unsupported action"},400);}catch(e){console.error(e);return json({error:e instanceof Error?e.message:"Provisioning failed"},500);}});