import { useCallback, useEffect, useMemo, useState } from "react";
import { C, addR, delR, gdb, supabase, updR } from "@/lg/data";

type Row = Record<string, any> & { id?: string | number };
const CLASSES = ["9", "10", "11", "12"];
const SECTIONS = ["A", "B", "C", "D"];
const card: React.CSSProperties = { background: "#fff", border: `1px solid ${C.border}`, borderRadius: 18, boxShadow: "0 4px 20px rgba(15,27,61,.07)" };
function Button({ children, onClick, outline = false, color = C.accent, disabled = false }: { children: React.ReactNode; onClick?: () => void; outline?: boolean; color?: string; disabled?: boolean }) { return <button type="button" disabled={disabled} onClick={onClick} style={{ border: outline ? `1.5px solid ${color}` : 0, background: outline ? "transparent" : color, color: outline ? color : "#fff", borderRadius: 10, padding: "9px 14px", fontWeight: 800, cursor: disabled ? "wait" : "pointer", opacity: disabled ? .6 : 1 }}>{children}</button>; }
function Field({ label, value, onChange, options, placeholder }: { label: string; value: string; onChange: (v: string) => void; options?: string[]; placeholder?: string }) { return <label style={{ display: "block" }}><span style={{ display: "block", fontSize: 12, fontWeight: 750, color: C.sub, marginBottom: 6 }}>{label}</span>{options ? <select value={value} onChange={e => onChange(e.target.value)} style={{ width: "100%", boxSizing: "border-box", padding: "10px 12px", border: `1.5px solid ${C.border}`, borderRadius: 10, background: "#F8FAFF" }}><option value="">Select…</option>{options.map(o => <option key={o} value={o}>{o}</option>)}</select> : <input value={value} onChange={e => onChange(e.target.value)} placeholder={placeholder} style={{ width: "100%", boxSizing: "border-box", padding: "10px 12px", border: `1.5px solid ${C.border}`, borderRadius: 10, background: "#F8FAFF" }} />}</label>; }
function Modal({ title, children, onClose }: { title: string; children: React.ReactNode; onClose: () => void }) { return <div onClick={onClose} style={{ position: "fixed", inset: 0, zIndex: 100, background: "rgba(15,27,61,.58)", display: "grid", placeItems: "center", padding: 16 }}><div onClick={e => e.stopPropagation()} style={{ width: "min(900px,100%)", maxHeight: "92vh", overflowY: "auto", background: "#fff", borderRadius: 20, padding: 24, boxShadow: "0 24px 80px rgba(0,0,0,.25)" }}><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 20 }}><h2 style={{ margin: 0, color: C.text, fontSize: 20 }}>{title}</h2><button type="button" onClick={onClose} style={{ border: 0, background: "#F1F5F9", borderRadius: 9, padding: 8 }}>✕</button></div>{children}</div></div>; }

export default function BatchesTimetablePage() {
  const [batches, setBatches] = useState<Row[]>([]); const [students, setStudents] = useState<Row[]>([]); const [memberships, setMemberships] = useState<Row[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState(""); const [batchModal, setBatchModal] = useState(false); const [studentModal, setStudentModal] = useState<Row | null>(null); const [editing, setEditing] = useState<Row | null>(null); const [deleteTarget, setDeleteTarget] = useState<Row | null>(null); const [query, setQuery] = useState(""); const [form, setForm] = useState({ name: "", cls: "", sec: "", capacity: "", status: "active", description: "" }); const [selectedStudents, setSelectedStudents] = useState<string[]>([]);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const [b,s,m] = await Promise.all([gdb("batches"), gdb("students"), gdb("batch_students")]); setBatches(b as Row[]); setStudents(s as Row[]); setMemberships(m as Row[]); } catch(e) { setError(e instanceof Error ? e.message : "Unable to load batches."); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const openCreate = () => { setEditing(null); setForm({ name: "", cls: "", sec: "", capacity: "", status: "active", description: "" }); setError(""); setBatchModal(true); };
  const openEdit = (b: Row) => { setEditing(b); setForm({ name: String(b.name ?? ""), cls: String(b.cls ?? ""), sec: String(b.sec ?? ""), capacity: b.capacity == null ? "" : String(b.capacity), status: String(b.status ?? "active"), description: String(b.description ?? "") }); setError(""); setBatchModal(true); };
  const saveBatch = async () => { if (!form.name.trim() || !form.cls) { setError("Batch Name and Class are required."); return; } const capacity = form.capacity.trim() ? Number(form.capacity) : null; if (capacity !== null && (!Number.isInteger(capacity) || capacity <= 0)) { setError("Capacity must be a positive whole number."); return; } setSaving(true); setError(""); try { const payload = { name: form.name.trim(), code: form.name.trim().toUpperCase().replace(/[^A-Z0-9]+/g, "-").replace(/^-|-$/g, ""), cls: form.cls, sec: form.sec || "All", capacity, status: form.status || "active", description: form.description.trim() }; if (editing) await updR("batches", editing.id, payload); else await addR("batches", { id: `batch-${Date.now()}`, ...payload }); setBatchModal(false); await load(); setSuccess(editing ? "Batch updated successfully." : "Batch created successfully."); } catch(e) { setError(e instanceof Error ? e.message : "Unable to save batch."); } finally { setSaving(false); } };
  const openStudents = (b: Row) => { setError(""); setStudentModal(b); setSelectedStudents(memberships.filter(m => String(m.batch_id) === String(b.id) && String(m.status ?? "active") === "active").map(m => String(m.student_id))); };
  const saveStudents = async () => { if (!studentModal) return; const batchId = String(studentModal.id); const current = memberships.filter(m => String(m.batch_id) === batchId && String(m.status ?? "active") === "active"); const currentIds = new Set(current.map(m => String(m.student_id))); const selected = new Set(selectedStudents); const additions = selectedStudents.filter(id => !currentIds.has(id)); const removals = current.filter(m => !selected.has(String(m.student_id))); const capacity = studentModal.capacity == null ? null : Number(studentModal.capacity); if (capacity !== null && selectedStudents.length > capacity) { setError(`This batch has a capacity of ${capacity}. You selected ${selectedStudents.length} students.`); return; } setSaving(true); setError(""); try { for (const membership of removals) { const { error } = await supabase.from("batch_students").delete().eq("batch_id", batchId).eq("student_id", String(membership.student_id)); if (error) throw error; } for (const studentId of additions) await addR("batch_students", { batch_id: batchId, student_id: studentId, status: "active" }); await load(); setStudentModal(null); setSuccess("Batch students updated successfully."); } catch(e) { setError(e instanceof Error ? e.message : "Unable to update batch students. A student may already belong to another active batch."); await load(); } finally { setSaving(false); } };
  const removeBatch = async () => { if (!deleteTarget) return; setSaving(true); setError(""); try { await delR("batches", deleteTarget.id); setDeleteTarget(null); await load(); setSuccess("Batch deleted successfully. Student accounts were kept."); } catch(e) { setError(e instanceof Error ? e.message : "Unable to delete batch."); setDeleteTarget(null); } finally { setSaving(false); } };
  const filtered = useMemo(() => { const q=query.trim().toLowerCase(); return q ? batches.filter(b => `${b.name} ${b.cls} ${b.sec}`.toLowerCase().includes(q)) : batches; }, [batches,query]);
  const countFor = (id:string|number|undefined) => memberships.filter(m => String(m.batch_id)===String(id) && String(m.status??"active")==="active").length;
  return <div style={{ padding:28, background:"#F7F9FF", minHeight:"100%" }}>
    {success && <div style={{ ...card,padding:12,marginBottom:16,color:"#15803D",background:"#F0FDF4" }}>✅ {success}</div>}{error && <div style={{ ...card,padding:12,marginBottom:16,color:C.red,background:"#FFF7F7" }}>{error}</div>}
    <div style={{ display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,marginBottom:20,flexWrap:"wrap" }}><div><h1 style={{ margin:0,color:C.text,fontSize:24 }}>Batches</h1><p style={{ margin:"5px 0 0",color:C.sub,fontSize:13 }}>Create student groups and manage the students inside each batch.</p></div><Button onClick={openCreate}>+ Create Batch</Button></div>
    <div style={{ ...card,padding:14,marginBottom:18 }}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search batch name, class or section…" style={{ width:"100%",boxSizing:"border-box",border:`1px solid ${C.border}`,borderRadius:10,padding:"11px 13px",background:"#F8FAFF" }} /></div>
    {loading ? <div style={{ ...card,padding:45,textAlign:"center",color:C.sub }}>Loading batches…</div> : filtered.length===0 ? <div style={{ ...card,padding:55,textAlign:"center" }}><div style={{ fontSize:42 }}>👥</div><h3 style={{ color:C.text }}>No batches yet</h3><p style={{ color:C.sub,fontSize:13 }}>Create your first batch and then add its students.</p><Button onClick={openCreate}>+ Create Batch</Button></div> : <div style={{ display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(310px,1fr))",gap:16 }}>{filtered.map(b=>{const count=countFor(b.id);const cap=b.capacity==null?null:Number(b.capacity);return <div key={String(b.id)} style={{ ...card,padding:20 }}><div style={{ display:"flex",justifyContent:"space-between",gap:10 }}><div><h3 style={{ margin:0,color:C.text }}>{b.name}</h3><div style={{ marginTop:5,color:C.sub,fontSize:12 }}>Class {b.cls}{b.sec&&b.sec!=="All"?` · Section ${b.sec}`:""}</div></div><span style={{ fontSize:10,fontWeight:800,color:b.status==="active"?"#15803D":C.red,background:b.status==="active"?"#DCFCE7":"#FEE2E2",padding:"4px 9px",borderRadius:20 }}>{b.status||"active"}</span></div><div style={{ margin:"18px 0",padding:14,borderRadius:12,background:"#F8FAFF" }}><div style={{ fontSize:26,fontWeight:900,color:C.accent }}>{count}{cap!==null&&<span style={{ fontSize:14,color:C.sub }}> / {cap}</span>}</div><div style={{ fontSize:11,color:C.sub }}>students in this batch</div></div>{b.description&&<p style={{ color:C.sub,fontSize:12,margin:"0 0 14px" }}>{b.description}</p>}<div style={{ display:"flex",gap:8,flexWrap:"wrap" }}><Button onClick={()=>openStudents(b)}>👥 Students</Button><Button outline onClick={()=>openEdit(b)}>Edit</Button><Button outline color={C.red} onClick={()=>setDeleteTarget(b)}>Delete</Button></div></div>})}</div>}
    {batchModal&&<Modal title={editing?"Edit Batch":"Create Batch"} onClose={()=>!saving&&setBatchModal(false)}><div style={{ display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:14 }}><Field label="Batch Name" value={form.name} onChange={v=>setForm(f=>({...f,name:v}))} placeholder="10 Morning"/><Field label="Class" value={form.cls} onChange={v=>setForm(f=>({...f,cls:v}))} options={CLASSES}/><Field label="Section (optional)" value={form.sec} onChange={v=>setForm(f=>({...f,sec:v}))} options={SECTIONS}/><Field label="Capacity (optional)" value={form.capacity} onChange={v=>setForm(f=>({...f,capacity:v}))} placeholder="30"/><Field label="Status" value={form.status} onChange={v=>setForm(f=>({...f,status:v}))} options={["active","inactive"]/><label style={{ gridColumn:"1 / -1" }}><span style={{ display:"block",fontSize:12,fontWeight:750,color:C.sub,marginBottom:6 }}>Description</span><textarea value={form.description} onChange={e=>setForm(f=>({...f,description:e.target.value}))} placeholder="Optional batch notes" style={{ width:"100%",minHeight:80,boxSizing:"border-box",padding:11,border:`1.5px solid ${C.border}`,borderRadius:10 }}/></label></div><div style={{ display:"flex",justifyContent:"flex-end",gap:8,marginTop:20 }}><Button outline onClick={()=>setBatchModal(false)}>Cancel</Button><Button disabled={saving} onClick={()=>void saveBatch()}>{saving?"Saving…":editing?"Save Changes":"Create Batch"}</Button></div></Modal>}
    {studentModal&&<Modal title={`Students — ${studentModal.name}`} onClose={()=>!saving&&setStudentModal(null)}><p style={{ color:C.sub,fontSize:13 }}>Select the active students who belong to this batch. A student can have only one active batch.</p><div style={{ maxHeight:430,overflowY:"auto",border:`1px solid ${C.border}`,borderRadius:12 }}>{students.filter(s=>String(s.status??"active")==="active").map(s=>{const checked=selectedStudents.includes(String(s.id));const other=memberships.find(m=>String(m.student_id)===String(s.id)&&String(m.status??"active")==="active"&&String(m.batch_id)!==String(studentModal.id));return <label key={String(s.id)} style={{ display:"flex",alignItems:"center",gap:12,padding:"11px 13px",borderBottom:`1px solid ${C.border}`,opacity:other?.5:1 }}><input type="checkbox" checked={checked} disabled={!!other} onChange={()=>setSelectedStudents(x=>checked?x.filter(id=>id!==String(s.id)):[...x,String(s.id)])}/><span style={{ flex:1 }}><b style={{ color:C.text,fontSize:13 }}>{s.name}</b><span style={{ display:"block",color:C.sub,fontSize:11 }}>{s.sid} · Class {s.cls}-{s.sec}{other?" · Already in another batch":""}</span></span></label>})}</div><div style={{ marginTop:12,fontSize:12,color:C.sub }}>{selectedStudents.length} students selected</div><div style={{ display:"flex",justifyContent:"flex-end",gap:8,marginTop:18 }}><Button outline onClick={()=>setStudentModal(null)}>Cancel</Button><Button disabled={saving} onClick={()=>void saveStudents()}>{saving?"Saving…":"Save Students"}</Button></div></Modal>}
    {deleteTarget&&<Modal title="Delete Batch" onClose={()=>!saving&&setDeleteTarget(null)}><p style={{ color:C.sub }}>Delete <b>{deleteTarget.name}</b>? Students will not be deleted; only their batch memberships will be removed.</p><div style={{ display:"flex",justifyContent:"flex-end",gap:8 }}><Button outline onClick={()=>setDeleteTarget(null)}>Cancel</Button><Button color={C.red} disabled={saving} onClick={()=>void removeBatch()}>{saving?"Deleting…":"Delete Batch"}</Button></div></Modal>}
  </div>;
}
