import { useCallback, useEffect, useState, type ReactNode } from "react";
import { C, addR, delR, gdb, updR } from "@/lg/data";
import AdminDashboard from "@/admin/dashboard/AdminDashboard";
import AdminRecordsPage from "@/admin/records/AdminRecordsPage";
import BatchesTimetablePage from "@/admin/batches/BatchesTimetablePage";
import HomeworkPage from "@/admin/HomeworkPage";
import ExamSchedulePage from "@/admin/examschedule/ExamSchedulePage";
import StudentResultsPage from "@/admin/results/StudentResultsPage";
import { MaterialsDrive } from "@/admin/MaterialsDrive";
import AnnouncementsPage from "@/admin/AnnouncementsPage";
import AdminMessagesPage from "@/admin/AdminMessagesPage";
import { AdminErrorBoundary } from "@/admin/AdminErrorBoundary";

type AdminUser = { id: string; name: string; phone: string; role: string; ref: string | null };
type View = "dashboard" | "students" | "teachers" | "batches" | "attendance" | "homework" | "examschedule" | "results" | "materials" | "fees" | "announcements" | "accounts" | "marks" | "search" | "messages";
type Row = Record<string, any> & { id?: string | number };

function Button({ children, onClick, color = C.accent, outline = false }: { children: ReactNode; onClick?: () => void; color?: string; outline?: boolean }) {
  return <button type="button" onClick={onClick} style={{ border: outline ? `1.5px solid ${color}` : 0, borderRadius: 10, padding: "9px 13px", background: outline ? "transparent" : color, color: outline ? color : "#fff", fontWeight: 800, cursor: "pointer" }}>{children}</button>;
}

const inputStyle: React.CSSProperties = { display: "block", width: "100%", boxSizing: "border-box", marginTop: 6, padding: "10px 12px", border: `1.5px solid ${C.border}`, borderRadius: 10, background: "#F8FAFF", color: C.text };
function Card({ children, style = {} }: { children: ReactNode; style?: React.CSSProperties }) { return <section style={{ background: "#fff", border: `1px solid ${C.border}`, borderRadius: 18, padding: 18, ...style }}>{children}</section>; }
function ErrorBox({ error }: { error: string }) { return error ? <div style={{ marginBottom: 12, padding: 11, borderRadius: 10, background: "#FFF1F2", color: C.red }}>{error}</div> : null; }

function AttendancePage() {
  const [rows, setRows] = useState<Row[]>([]), [students, setStudents] = useState<Row[]>([]), [error, setError] = useState(""), [form, setForm] = useState({ sid: "", date: new Date().toISOString().slice(0, 10), status: "present", note: "" });
  const load = useCallback(async () => { try { const [a, s] = await Promise.all([gdb("attendance"), gdb("students")]); setRows(a || []); setStudents(s || []); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load attendance."); } }, []);
  useEffect(() => { void load(); }, [load]);
  const save = async () => { if (!form.sid || !form.date) { setError("Student and date are required."); return; } try { await addR("attendance", { id: `att-${Date.now()}`, ...form, by: "admin" }); setForm({ sid: "", date: new Date().toISOString().slice(0, 10), status: "present", note: "" }); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Unable to save attendance."); } };
  const name = (id: any) => students.find(s => String(s.id) === String(id) || String(s.sid) === String(id))?.name || String(id || "Unknown");
  return <div style={{ padding: 24 }}><ErrorBox error={error}/><Card style={{ marginBottom: 14 }}><h3 style={{ marginTop: 0 }}>Mark Attendance</h3><div style={{ display: "grid", gap: 10, gridTemplateColumns: "repeat(auto-fit,minmax(170px,1fr))" }}><select value={form.sid} onChange={e => setForm({ ...form, sid: e.target.value })} style={inputStyle}><option value="">Select student</option>{students.map(s => <option key={String(s.id)} value={String(s.id)}>{s.name || s.sid || s.id}</option>)}</select><input type="date" value={form.date} onChange={e => setForm({ ...form, date: e.target.value })} style={inputStyle}/><select value={form.status} onChange={e => setForm({ ...form, status: e.target.value })} style={inputStyle}><option value="present">Present</option><option value="absent">Absent</option><option value="leave">Leave</option></select><input value={form.note} onChange={e => setForm({ ...form, note: e.target.value })} placeholder="Note" style={inputStyle}/></div><div style={{ marginTop: 12 }}><Button onClick={() => void save()}>＋ Mark Attendance</Button></div></Card><Card><table style={{ width: "100%", borderCollapse: "collapse" }}><thead><tr><th>Student</th><th>Date</th><th>Status</th><th>Note</th></tr></thead><tbody>{rows.map((r, i) => <tr key={String(r.id || i)}><td>{name(r.sid)}</td><td>{r.date}</td><td>{String(r.status || "").toUpperCase()}</td><td>{r.note || "—"}</td></tr>)}</tbody></table></Card></div>;
}

function FeesPage() {
  const [rows, setRows] = useState<Row[]>([]), [students, setStudents] = useState<Row[]>([]), [error, setError] = useState(""), [form, setForm] = useState({ sid: "", desc: "", amount: "", due: "", status: "pending" });
  const load = useCallback(async () => { try { const [f, s] = await Promise.all([gdb("fees"), gdb("students")]); setRows(f || []); setStudents(s || []); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load fees."); } }, []);
  useEffect(() => { void load(); }, [load]);
  const save = async () => { const amount = Number(form.amount); if (!form.sid || !form.desc.trim() || !Number.isFinite(amount) || amount < 0 || !form.due) { setError("Student, description, amount and due date are required."); return; } try { await addR("fees", { id: `fee-${Date.now()}`, ...form, amount }); setForm({ sid: "", desc: "", amount: "", due: "", status: "pending" }); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Unable to save fee."); } };
  const name = (id: any) => students.find(s => String(s.id) === String(id) || String(s.sid) === String(id))?.name || String(id || "Unknown");
  return <div style={{ padding: 24 }}><ErrorBox error={error}/><Card style={{ marginBottom: 14 }}><h3 style={{ marginTop: 0 }}>Add Fee</h3><div style={{ display: "grid", gap: 10, gridTemplateColumns: "repeat(auto-fit,minmax(170px,1fr))" }}><select value={form.sid} onChange={e => setForm({ ...form, sid: e.target.value })} style={inputStyle}><option value="">Select student</option>{students.map(s => <option key={String(s.id)} value={String(s.id)}>{s.name || s.sid || s.id}</option>)}</select><input value={form.desc} onChange={e => setForm({ ...form, desc: e.target.value })} placeholder="Description" style={inputStyle}/><input type="number" value={form.amount} onChange={e => setForm({ ...form, amount: e.target.value })} placeholder="Amount" style={inputStyle}/><input type="date" value={form.due} onChange={e => setForm({ ...form, due: e.target.value })} style={inputStyle}/><select value={form.status} onChange={e => setForm({ ...form, status: e.target.value })} style={inputStyle}><option value="pending">Pending</option><option value="paid">Paid</option><option value="overdue">Overdue</option></select></div><div style={{ marginTop: 12 }}><Button onClick={() => void save()}>＋ Add Fee</Button></div></Card><Card><table style={{ width: "100%", borderCollapse: "collapse" }}><thead><tr><th>Student</th><th>Description</th><th>Amount</th><th>Due</th><th>Status</th></tr></thead><tbody>{rows.map((r, i) => <tr key={String(r.id || i)}><td>{name(r.sid)}</td><td>{r.desc}</td><td>₹{Number(r.amount || 0).toLocaleString("en-IN")}</td><td>{r.due}</td><td>{String(r.status || "").toUpperCase()}</td></tr>)}</tbody></table></Card></div>;
}

function AccountsPage() {
  const [rows, setRows] = useState<Row[]>([]), [error, setError] = useState("");
  const load = useCallback(async () => { try { setRows((await gdb("users")).filter((r: Row) => r.role !== "admin")); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load accounts."); } }, []);
  useEffect(() => { void load(); }, [load]);
  const toggle = async (r: Row) => { try { await updR("users", r.id, { status: r.status === "active" ? "inactive" : "active" }); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Unable to update account."); } };
  return <div style={{ padding: 24 }}><ErrorBox error={error}/><Card><table style={{ width: "100%", borderCollapse: "collapse" }}><thead><tr><th>Name</th><th>Role</th><th>Login ID</th><th>Status</th><th>Action</th></tr></thead><tbody>{rows.map((r, i) => <tr key={String(r.id || i)}><td>{r.name || "—"}</td><td>{String(r.role || "").toUpperCase()}</td><td>{r.phone || "—"}</td><td>{String(r.status || "active").toUpperCase()}</td><td><Button outline onClick={() => void toggle(r)}>{r.status === "active" ? "Disable" : "Activate"}</Button></td></tr>)}</tbody></table></Card></div>;
}

function MarksPage() {
  const [rows, setRows] = useState<Row[]>([]), [students, setStudents] = useState<Row[]>([]), [error, setError] = useState("");
  useEffect(() => { Promise.all([gdb("marks"), gdb("students")]).then(([m, s]) => { setRows(m || []); setStudents(s || []); }).catch(e => setError(e instanceof Error ? e.message : "Unable to load marks.")); }, []);
  const name = (id: any) => students.find(s => String(s.id) === String(id) || String(s.sid) === String(id))?.name || String(id || "Unknown");
  const pct = (r: Row) => Math.round(Number(r.marks || 0) / Math.max(1, Number(r.total || 100)) * 100);
  return <div style={{ padding: 24 }}><ErrorBox error={error}/><Card><table style={{ width: "100%", borderCollapse: "collapse" }}><thead><tr><th>Student</th><th>Subject</th><th>Exam</th><th>Marks</th><th>Score</th><th>Date</th></tr></thead><tbody>{rows.map((r, i) => <tr key={String(r.id || i)}><td>{name(r.sid)}</td><td>{r.subject || "—"}</td><td>{r.exam || "—"}</td><td>{r.marks || 0}/{r.total || 100}</td><td>{pct(r)}%</td><td>{r.date || "—"}</td></tr>)}</tbody></table></Card></div>;
}

function SearchPage() {
  const [students, setStudents] = useState<Row[]>([]), [teachers, setTeachers] = useState<Row[]>([]), [q, setQ] = useState(""), [type, setType] = useState<"student" | "teacher">("student"), [error, setError] = useState("");
  useEffect(() => { Promise.all([gdb("students"), gdb("teachers")]).then(([s, t]) => { setStudents(s || []); setTeachers(t || []); }).catch(e => setError(e instanceof Error ? e.message : "Unable to load profiles.")); }, []);
  const list = (type === "student" ? students : teachers).filter(r => `${r.name || ""} ${type === "student" ? r.sid || "" : r.tid || ""} ${r.phone || ""}`.toLowerCase().includes(q.toLowerCase()));
  return <div style={{ padding: 24 }}><ErrorBox error={error}/><Card style={{ marginBottom: 14 }}><div style={{ display: "flex", gap: 8 }}><Button outline={type !== "student"} onClick={() => setType("student")}>🎓 Students</Button><Button outline={type !== "teacher"} onClick={() => setType("teacher")}>👨‍🏫 Teachers</Button></div><input value={q} onChange={e => setQ(e.target.value)} placeholder="Search name, ID or phone…" style={inputStyle}/></Card><Card><table style={{ width: "100%", borderCollapse: "collapse" }}><thead><tr><th>ID</th><th>Name</th><th>Subject/Class</th><th>Phone</th></tr></thead><tbody>{list.map((r, i) => <tr key={String(r.id || i)}><td>{type === "student" ? r.sid : r.tid}</td><td>{r.name}</td><td>{type === "student" ? `${r.cls || "—"}-${r.sec || "—"}` : r.subject || "—"}</td><td>{r.phone || "—"}</td></tr>)}</tbody></table></Card></div>;
}

const NAV: Array<[View, string, string]> = [["dashboard", "🏠", "Dashboard"], ["students", "🎓", "Students"], ["teachers", "👨‍🏫", "Teachers"], ["batches", "👥", "Batches & Timetable"], ["attendance", "✅", "Attendance"], ["homework", "📝", "Homework"], ["examschedule", "📋", "Exam Schedule"], ["results", "🏆", "Student Results"], ["materials", "📚", "Study Materials"], ["fees", "💰", "Fees"], ["announcements", "📢", "Announcements"], ["accounts", "🔐", "User Accounts"], ["marks", "📊", "Marks Overview"], ["search", "🔍", "Search Profiles"], ["messages", "✉️", "Messages"]];
const META: Record<View, string> = { dashboard: "Dashboard", students: "Students", teachers: "Teachers", batches: "Batches & Timetable", attendance: "Attendance", homework: "Homework", examschedule: "Exam Schedule", results: "Student Results", materials: "Study Materials", fees: "Fees", announcements: "Announcements", accounts: "User Accounts", marks: "Marks Overview", search: "Search Profiles", messages: "Messages" };

export function AdminWithDrive({ user, onLogout }: { user: AdminUser; onLogout: () => void }) {
  const [view, setView] = useState<View>("dashboard");
  const content = view === "dashboard" ? <AdminDashboard /> : view === "students" ? <AdminRecordsPage kind="students" /> : view === "teachers" ? <AdminRecordsPage kind="teachers" /> : view === "batches" ? <BatchesTimetablePage /> : view === "attendance" ? <AttendancePage /> : view === "homework" ? <HomeworkPage /> : view === "examschedule" ? <ExamSchedulePage /> : view === "results" ? <StudentResultsPage /> : view === "materials" ? <MaterialsDrive /> : view === "fees" ? <FeesPage /> : view === "announcements" ? <AnnouncementsPage /> : view === "accounts" ? <AccountsPage /> : view === "marks" ? <MarksPage /> : view === "search" ? <SearchPage /> : <AdminMessagesPage user={{ ...user, ref: user.ref || user.id }} />;
  return <div style={{ minHeight: "100vh", background: C.bg, color: C.text, fontFamily: "Poppins,system-ui,sans-serif", display: "flex" }}><aside style={{ width: 235, minHeight: "100vh", background: C.sidebar, padding: "0 11px 16px", display: "flex", flexDirection: "column", flexShrink: 0 }}><div style={{ padding: "20px 8px 16px", borderBottom: "1px solid #ffffff12" }}><div style={{ color: "#fff", fontWeight: 900, fontSize: 18 }}>Learner's <span style={{ color: C.gold }}>Guide</span></div><div style={{ marginTop: 8, color: C.red, fontSize: 11, fontWeight: 800 }}>🔴 ADMIN PANEL · FULL ACCESS</div></div><nav style={{ flex: 1, overflowY: "auto", marginTop: 10 }}>{NAV.map(([key, icon, label]) => <button key={key} type="button" onClick={() => setView(key)} style={{ width: "100%", border: 0, borderRadius: 11, padding: "10px 12px", margin: "2px 0", background: view === key ? C.accent : "transparent", color: view === key ? "#fff" : "#ffffffb5", display: "flex", alignItems: "center", gap: 11, cursor: "pointer", textAlign: "left", fontWeight: view === key ? 800 : 650, fontSize: 13 }}><span style={{ fontSize: 17 }}>{icon}</span>{label}</button>)}</nav><div style={{ borderTop: "1px solid #ffffff12", paddingTop: 12 }}><div style={{ color: "#fff", fontSize: 12, fontWeight: 750, padding: "7px 8px 10px" }}>👑 {user.name || "Administrator"}</div><Button color="#8f2020" onClick={onLogout}>🚪 Logout</Button></div></aside><main style={{ flex: 1, minWidth: 0, minHeight: "100vh", overflowY: "auto" }}><header style={{ padding: "18px 24px", background: "#fff", borderBottom: `1px solid ${C.border}`, display: "flex", justifyContent: "space-between", alignItems: "center" }}><h1 style={{ margin: 0, fontSize: 20 }}>{META[view]}</h1><Button outline onClick={() => window.dispatchEvent(new Event("lg-admin-refresh"))}>↻ Refresh</Button></header><AdminErrorBoundary section={META[view]}>{content}</AdminErrorBoundary></main></div>;
}
