import { useCallback, useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import { addR, delR, gdb, updR } from "@/lg/data";
import { supabase } from "@/lg/supabase";
import { LGLogo } from "@/lg/ui";

const A = { bg: "#F0F4FF", sidebar: "#0F1B3D", accent: "#4361EE", gold: "#F5A623", green: "#22C55E", red: "#EF4444", amber: "#F59E0B", purple: "#8B5CF6", cyan: "#06B6D4", text: "#0F1B3D", sub: "#64748B", border: "#E2E8F0", light: "#F8FAFF" };
type PageKey = "dashboard" | "students" | "teachers" | "batches" | "attendance" | "homework" | "examschedule" | "materials" | "fees" | "announcements" | "accounts" | "search";
type Row = Record<string, any> & { id?: string | number };
type AdminUser = { id: string; name: string; phone: string; role: string; ref: string | null };
type Props = { user: AdminUser; onLogout: () => void };
const NAV: Array<[PageKey, string, string]> = [["dashboard", "🏠", "Dashboard"], ["students", "🎓", "Students"], ["teachers", "👨‍🏫", "Teachers"], ["batches", "👥", "Batches & Timetable"], ["attendance", "✅", "Attendance"], ["homework", "📝", "Homework"], ["examschedule", "📋", "Exam Schedule"], ["materials", "📚", "Study Materials"], ["fees", "💰", "Fees"], ["announcements", "📢", "Announcements"], ["accounts", "🔐", "User Accounts"], ["search", "🔍", "Search Profiles"]];
const META: Record<PageKey, { title: string; subtitle: string; table?: string }> = { dashboard: { title: "Dashboard", subtitle: "Full overview of your institute" }, students: { title: "Students", subtitle: "Add, edit, delete students — auto creates login accounts", table: "students" }, teachers: { title: "Teachers", subtitle: "Manage teacher accounts and subjects", table: "teachers" }, batches: { title: "Batches & Timetable", subtitle: "Create batches, assign timetable slots and teachers", table: "batches" }, attendance: { title: "Attendance", subtitle: "View all attendance records", table: "attendance" }, homework: { title: "Homework", subtitle: "Monitor homework assigned by teachers", table: "homework" }, examschedule: { title: "Exam Schedule", subtitle: "Schedule upcoming exams for classes", table: "examschedule" }, materials: { title: "Study Materials", subtitle: "Upload study materials — maximum 50 MB per file", table: "materials" }, fees: { title: "Fees", subtitle: "Track and manage fee payments", table: "fees" }, announcements: { title: "Announcements", subtitle: "Post announcements to all roles", table: "announcements" }, accounts: { title: "User Accounts", subtitle: "View authorized login accounts", table: "users" }, search: { title: "Search Profiles", subtitle: "Search student or teacher — full profile view" } };
const subjects = ["Mathematics", "Science", "English", "Hindi", "Computer", "Physics", "Chemistry", "Biology", "History", "Geography", "Sanskrit", "Physical Education"];
const days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
const slots = ["7:00–8:00 AM", "8:00–9:00 AM", "9:00–10:00 AM", "10:00–11:00 AM", "11:00 AM–12:00 PM", "12:00–1:00 PM", "1:00–2:00 PM", "2:00–3:00 PM", "3:00–4:00 PM", "4:00–5:00 PM"];
const gradeOptions = ["Nursery", "LKG", "UKG", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"];
const sectionOptions = ["A", "B", "C", "D", "All"];
const css = `*{box-sizing:border-box}.admin{min-height:100vh;background:${A.bg};color:${A.text};font-family:Poppins,system-ui,sans-serif}.admin button,.admin input,.admin select,.admin textarea{font:inherit}.nav{border:0;background:transparent;color:#ffffff8c;width:100%;padding:11px 14px;margin:3px 0;border-radius:12px;text-align:left;display:flex;align-items:center;gap:12px;cursor:pointer}.nav:hover{background:#ffffff12}.nav.active{background:${A.accent};color:#fff;box-shadow:0 6px 20px #4361ee59}.btn{border:0;border-radius:12px;padding:10px 16px;font-weight:750;cursor:pointer;display:inline-flex;align-items:center;gap:7px}.btn:hover{filter:brightness(1.05);transform:translateY(-1px)}.card{background:#fff;border:1px solid #eef2ff;border-radius:20px;box-shadow:0 4px 20px #0f1b3d12}.modal{position:fixed;inset:0;background:#0f1b3d99;z-index:50;display:grid;place-items:center;padding:16px}.modalbox{background:#fff;border-radius:22px;width:min(720px,100%);max-height:92vh;overflow:auto;padding:26px;box-shadow:0 24px 72px #0f1b3d30}.field{margin-bottom:13px}.field label{display:block;font-size:12px;font-weight:750;color:${A.sub};margin-bottom:6px}.field input,.field select,.field textarea{width:100%;padding:11px 13px;border:1.5px solid ${A.border};border-radius:11px;background:${A.light};color:${A.text};outline:none}.field textarea{min-height:90px;resize:vertical}.tablewrap{overflow:auto}.table{width:100%;border-collapse:collapse;font-size:13px}.table th{background:${A.light};padding:12px 14px;text-align:left;color:${A.sub};white-space:nowrap}.table td{padding:12px 14px;border-top:1px solid ${A.border};white-space:nowrap}.table tr:hover td{background:#f8faff}.badge{display:inline-block;padding:3px 10px;border-radius:20px;font-size:11px;font-weight:800}.grid{display:grid;gap:16px}@media(max-width:900px){.shell{display:block!important}.side{position:relative!important;width:100%!important;min-height:auto!important}.navrow{display:flex;overflow-x:auto;padding-bottom:6px}.nav{width:auto;white-space:nowrap}.sidebottom{display:none!important}.main{min-height:auto!important}.top{padding:16px!important}.content{padding:16px!important}.twocol{grid-template-columns:1fr!important}.stats{grid-template-columns:repeat(2,minmax(0,1fr))!important}}@media(max-width:520px){.stats{grid-template-columns:1fr!important}.modalbox{padding:18px}.actions{flex-wrap:wrap}.actions>*{flex:1}.top h1{font-size:18px!important}}`;

function Sidebar({ page, setPage, onLogout }: { page: PageKey; setPage: (p: PageKey) => void; onLogout: () => void }) { return <aside className="side" style={{ width: 235, minHeight: "100vh", background: A.sidebar, padding: "0 12px 18px", position: "sticky", top: 0, display: "flex", flexDirection: "column", flexShrink: 0 }}><div style={{ padding: "20px 8px 16px", borderBottom: "1px solid #ffffff12" }}><div style={{ display: "flex", alignItems: "center", gap: 10 }}><div style={{ width: 42, height: 42, borderRadius: 12, background: "#fff", display: "grid", placeItems: "center", padding: 4 }}><LGLogo size={34} showText={false} /></div><div><b style={{ display: "block", color: "#fff", fontSize: 16 }}>Learner's</b><b style={{ display: "block", color: A.gold, fontSize: 16, marginTop: -4 }}>Guide</b></div></div><div style={{ marginTop: 12, color: A.red, fontSize: 11, fontWeight: 800 }}>🔴 ADMIN PANEL</div></div><nav className="navrow" style={{ flex: 1, overflowY: "auto", padding: "14px 0" }}>{NAV.map(([k, ic, l]) => <button key={k} className={`nav ${page === k ? "active" : ""}`} onClick={() => setPage(k)}><span style={{ fontSize: 18 }}>{ic}</span>{l}</button>)}</nav><div className="sidebottom" style={{ borderTop: "1px solid #ffffff12", paddingTop: 14 }}><div style={{ color: "#fff", fontWeight: 750, padding: 8 }}>👑 Admin <span style={{ display: "block", fontSize: 11, color: "#ffffff73", fontWeight: 500 }}>Full Access</span></div><button className="btn" onClick={onLogout} style={{ width: "100%", background: "#8f2020", color: "#fff", justifyContent: "center" }}>🚪 Logout</button></div></aside>; }

function Top({ meta }: { meta: { title: string; subtitle: string } }) { return <header className="top" style={{ display: "flex", justifyContent: "space-between", alignItems: "center", padding: "20px 28px", background: "#fff", borderBottom: `1px solid ${A.border}` }}><div><h1 style={{ margin: 0, fontSize: 20 }}>{meta.title}</h1><div style={{ fontSize: 13, color: A.sub }}>{meta.subtitle}</div></div></header>; }

export function ReferenceAdminPanel({ user, onLogout }: Props) { const [page, setPage] = useState<PageKey>("dashboard"); const [data, setData] = useState<Record<string, Row[]>>({}); const load = useCallback(async()=>{try{const tables=["students","teachers","batches","attendance","homework","examschedule","materials","fees","announcements","users"];const all=await Promise.all(tables.map(t=>gdb(t)));setData(Object.fromEntries(tables.map((t,i)=>[t,all[i]||[]])))}catch(e){console.error("admin load",e)}},[]);useEffect(()=>{void load()},[load]); const meta=META[page]; const content=page==="dashboard"?<div className="content" style={{padding:28}}><div className="grid stats" style={{gridTemplateColumns:"repeat(4,minmax(0,1fr))"}}>{[["🎓","Students",data.students?.length||0],["👨‍🏫","Teachers",data.teachers?.length||0],["✅","Attendance",data.attendance?.length||0],["💰","Fee Records",data.fees?.length||0]].map(([i,l,v])=><div key={l} className="card" style={{padding:18}}><div style={{fontSize:24}}>{i}</div><div style={{fontSize:11,color:A.sub}}>{l}</div><b style={{fontSize:25}}>{v}</b></div>)}</div></div>:<div className="content" style={{padding:28}}><div className="card" style={{padding:18}}><h3 style={{marginTop:0}}>{meta.title}</h3><p style={{color:A.sub,fontSize:13}}>This section remains available through the production Admin modules.</p></div></div>; return <div className="admin shell" style={{display:"flex"}}><style>{css}</style><Sidebar page={page} setPage={setPage} onLogout={onLogout}/><div className="main" style={{flex:1,minHeight:"100vh",display:"flex",flexDirection:"column"}}><Top meta={meta}/>{content}</div></div>; }
