import React,{useState}from"react";
import {C,lsG}from"@/lg/data";
import {PDFViewer}from"@/lg/panels";
import {ParentNotifications}from"@/lg/ParentNotifications";
import {Card,Badge,Sec,Shell,AppBar}from"@/lg/ui";
export function PTHome({child}){const att=lsG("attendance").filter(a=>a.sid===child?.id);const rate=att.length?Math.round(att.filter(a=>a.status==="present").length/att.length*100):0;const hw=child?lsG("homework").filter(h=>h.cls===child.cls&&h.sec===child.sec):[];const fees=lsG("fees").filter(f=>f.sid===child?.id&&f.status!=="paid");const ann=lsG("announcements").filter(a=>a.target==="all").slice(0,2);return <div><Card style={{marginBottom:16,background:"linear-gradient(135deg,#22C55E,#16A34A)",border:"none"}}><div style={{fontSize:19,fontWeight:900,color:"#fff"}}>{child?.name}</div><div style={{fontSize:12,color:"rgba(255,255,255,.7)"}}>Class {child?.cls}-{child?.sec} · {child?.sid}</div><div style={{display:"flex",gap:10,marginTop:13}}>{[[`${rate}%`,"Attendance"],[hw.length,"HW Pending"],[fees.length,"Fee Dues"]].map(([v,l])=><div key={l} style={{flex:1,background:"rgba(255,255,255,.15)",borderRadius:11,padding:9,textAlign:"center"}}><div style={{fontSize:19,fontWeight:900,color:"#fff"}}>{v}</div><div style={{fontSize:10,color:"rgba(255,255,255,.65)"}}>{l}</div></div>)}</div></Card><Sec title="Recent Attendance 📋"/>{att.slice(-4).reverse().map(a=><Card key={a.id} style={{marginBottom:8,display:"flex",justifyContent:"space-between"}}><div>{a.date}</div><Badge label={a.status}/></Card>)}<Sec title="Announcements 📢"/>{ann.map(a=><Card key={a.id} style={{marginBottom:9}}><div style={{fontWeight:700}}>{a.title}</div><div style={{fontSize:12,color:C.sub}}>{a.desc}</div></Card>)}</div>}
export function PTAttendance({child}){const att=lsG("attendance").filter(a=>a.sid===child?.id);const rate=att.length?Math.round(att.filter(a=>a.status==="present").length/att.length*100):0;return <div><Card style={{textAlign:"center",marginBottom:16,padding:26}}><div style={{fontSize:13,color:C.sub}}>Overall Attendance</div><div style={{fontSize:50,fontWeight:900,color:rate>=85?"#22C55E":rate>=70?"#F59E0B":"#EF4444"}}>{rate}%</div></Card><Sec title="Attendance Log"/>{[...att].reverse().map(a=><Card key={a.id} style={{marginBottom:7,display:"flex",justifyContent:"space-between"}}><div>{a.date}</div><Badge label={a.status}/></Card>)}</div>}
export function PTFees({child}){const fees=lsG("fees").filter(f=>f.sid===child?.id);const total=fees.reduce((s,f)=>s+Number(f.amount||0),0),paid=fees.filter(f=>f.status==="paid").reduce((s,f)=>s+Number(f.amount||0),0);return <div><Card style={{marginBottom:16,background:"linear-gradient(135deg,#22C55E,#16A34A)",border:"none"}}><div style={{color:"#fff",fontSize:26,fontWeight:900}}>₹{total.toLocaleString()}</div><div style={{color:"rgba(255,255,255,.8)",fontSize:12}}>Paid ₹{paid.toLocaleString()} · Due ₹{(total-paid).toLocaleString()}</div></Card><Sec title="Fee Details 💰"/>{fees.map(f=><Card key={f.id} style={{marginBottom:9,display:"flex",justifyContent:"space-between"}}><div><div style={{fontWeight:700}}>{f.desc}</div><div style={{fontSize:11,color:C.sub}}>Due: {f.due}</div></div><Badge label={f.status}/></Card>)}</div>}
export function ParentApp({user,onLogout}){const[showNotif,setShowNotif]=useState(false),[tab,setTab]=useState("home"),child=lsG("students").find(s=>s.id===user.ref),tabs=[{key:"home",icon:"🏠",label:"Home"},{key:"attendance",icon:"✅",label:"Attend."},{key:"homework",icon:"📝",label:"HW"},{key:"fees",icon:"💰",label:"Fees"},{key:"news",icon:"📢",label:"News"}];const content=tab==="home"?<PTHome child={child}/>:tab==="attendance"?<PTAttendance child={child}/>:tab==="fees"?<PTFees child={child}/>:tab==="news"?<div><Sec title="Announcements 📢"/>{lsG("announcements").map(a=><Card key={a.id} style={{marginBottom:10}}><div style={{fontWeight:800}}>{a.title}</div><div style={{fontSize:12,color:C.sub}}>{a.desc}</div></Card>)}</div>:<div><Sec title="Homework 📝"/>{(child?lsG("homework").filter(h=>h.cls===child.cls&&h.sec===child.sec):[]).map(h=><Card key={h.id} style={{marginBottom:10}}><Badge label={h.subject}/><div style={{fontWeight:700,marginTop:7}}>{h.desc}</div><div style={{fontSize:11,color:C.sub}}>Due: {h.due}</div>{h.pdfName&&<PDFViewer pdfData={h.pdfData} pdfName={h.pdfName}/>}</Card>)}</div>;return <><Shell header={<AppBar name={user.name} role="parent" userId={user.id} onLogout={onLogout} onNotif={()=>setShowNotif(true)}/>} tabs={tabs} activeTab={tab} setTab={setTab}>{content}</Shell>{showNotif&&<ParentNotifications onClose={()=>setShowNotif(false)}/>}</>}
