import React,{useEffect,useState}from"react";
import {C,lsG,gdb,addR}from"@/lg/data";
import {Badge,Card,Sec,Shell,AppBar}from"@/lg/ui";
import {NotifPanel,MessagingPanel,PDFViewer}from"@/lg/panels";
import {STMarks}from"@/lg/marks";
import {STHome,STTimetable}from"@/lg/student";

export function STAttendance({student}){const rows=lsG("attendance").filter(a=>String(a.sid)===String(student?.id));const present=rows.filter(a=>a.status==="present").length;const absent=rows.filter(a=>a.status==="absent").length;const leave=rows.filter(a=>a.status==="leave").length;const rate=rows.length?Math.round(present/rows.length*100):0;return <div><Card style={{textAlign:"center",padding:24,marginBottom:16}}><div style={{fontSize:34,fontWeight:900,color:rate>=75?C.green:C.red}}>{rate}%</div><div style={{fontSize:12,color:C.sub}}>Attendance</div><div style={{display:"flex",justifyContent:"center",gap:24,marginTop:16}}><div>✅ {present}<div style={{fontSize:10,color:C.sub}}>Present</div></div><div>❌ {absent}<div style={{fontSize:10,color:C.sub}}>Absent</div></div><div>🟡 {leave}<div style={{fontSize:10,color:C.sub}}>Leave</div></div></div></Card><Sec title="Attendance Log 📋"/>{rows.length?rows.slice().reverse().map(a=><Card key={a.id} style={{marginBottom:8,display:"flex",justifyContent:"space-between"}}><span>{a.date}</span><Badge label={a.status}/></Card>):<Card style={{textAlign:"center",padding:24,color:C.sub}}>No attendance records yet.</Card>}</div>}

export function STHomework({student}){const rows=student?lsG("homework").filter(h=>String(h.cls)===String(student.cls)&&String(h.sec)===String(student.sec)):[];return <div><Sec title={`Homework (${rows.length}) 📝`}/>{rows.length?rows.map(h=><Card key={h.id} style={{marginBottom:10}}><div style={{display:"flex",justifyContent:"space-between",gap:10}}><Badge label={h.subject}/><span style={{fontSize:11,color:C.sub}}>Due: {h.due}</span></div><div style={{fontWeight:700,color:C.text,marginTop:8}}>{h.desc}</div>{h.pdfName&&<PDFViewer pdfData={h.pdfData} pdfName={h.pdfName}/>}</Card>):<Card style={{textAlign:"center",padding:28,color:C.sub}}>No homework right now 🎉</Card>}</div>}

export function STMaterials(){const [rows,setRows]=useState([]);const [error,setError]=useState("");useEffect(()=>{void gdb("materials").then(d=>setRows(Array.isArray(d)?d:[])).catch(e=>setError(e?.message||"Unable to load materials"))},[]);return <div><Sec title="Study Materials 📚"/>{error&&<Card style={{color:C.red,marginBottom:10}}>{error}</Card>}{rows.length?rows.map(m=><Card key={m.id} style={{marginBottom:10}}><div style={{fontWeight:800,color:C.text}}>{m.title||m.name||"Material"}</div><div style={{fontSize:11,color:C.sub,marginTop:4}}>{m.subject||""}{m.desc?` · ${m.desc}`:""}</div>{m.pdfData&&<PDFViewer pdfData={m.pdfData} pdfName={m.pdfName||m.name}/>}</Card>):!error&&<Card style={{textAlign:"center",padding:28,color:C.sub}}>No study materials yet.</Card>}</div>}

export function STFees({student}){const rows=lsG("fees").filter(f=>String(f.sid)===String(student?.id));const total=rows.reduce((s,f)=>s+Number(f.amount||0),0);const paid=rows.filter(f=>f.status==="paid").reduce((s,f)=>s+Number(f.amount||0),0);return <div><Card style={{marginBottom:16}}><div style={{fontSize:12,color:C.sub}}>Total Fees</div><div style={{fontSize:26,fontWeight:900,color:C.text}}>₹{total.toLocaleString()}</div><div style={{fontSize:12,color:C.green}}>Paid ₹{paid.toLocaleString()} · Pending ₹{(total-paid).toLocaleString()}</div></Card><Sec title="Fee Records 💰"/>{rows.length?rows.map(f=><Card key={f.id} style={{marginBottom:9,display:"flex",justifyContent:"space-between"}}><div><div style={{fontWeight:700,color:C.text}}>{f.desc}</div><div style={{fontSize:11,color:C.sub}}>Due: {f.due}</div></div><div style={{textAlign:"right"}}>₹{Number(f.amount||0).toLocaleString()}<div><Badge label={f.status}/></div></div></Card>):<Card style={{textAlign:"center",padding:24,color:C.sub}}>No fee records yet.</Card>}</div>}

export function STExamSchedule({student}){const [rows,setRows]=useState(()=>lsG("examschedule"));useEffect(()=>{void gdb("examschedule").then(d=>setRows(Array.isArray(d)?d:[])).catch(()=>{})},[]);const today=new Date().toISOString().slice(0,10);const mine=rows.filter(e=>(!e.cls||String(e.cls)===String(student?.cls))&&(!e.sec||String(e.sec)===String(student?.sec)));const upcoming=mine.filter(e=>String(e.date)>=today).sort((a,b)=>String(a.date).localeCompare(String(b.date)));return <div><Sec title={`Upcoming Exams 📋 (${upcoming.length})`}/>{upcoming.length?upcoming.map(e=><Card key={e.id} style={{marginBottom:10}}><div style={{fontWeight:800,color:C.text}}>{e.title||e.subject}</div><div style={{fontSize:11,color:C.sub,marginTop:5}}>{e.date} · {e.startTime||""}{e.endTime?`–${e.endTime}`:""}{e.venue?` · ${e.venue}`:""}</div><div style={{fontSize:11,color:C.accent,marginTop:4}}>Marks: {e.totalMarks??"—"}</div></Card>):<Card style={{textAlign:"center",padding:28,color:C.sub}}>No upcoming exams.</Card>}</div>}

export function STAnnouncements(){const rows=lsG("announcements");return <div><Sec title="Announcements 📢"/>{rows.length?rows.map(a=><Card key={a.id} style={{marginBottom:10}}><div style={{fontWeight:800,color:C.text}}>{a.title}</div><div style={{fontSize:12,color:C.sub,marginTop:5}}>{a.desc}</div><div style={{fontSize:10,color:C.sub,marginTop:7}}>{a.date}</div></Card>):<Card style={{textAlign:"center",padding:24,color:C.sub}}>No announcements.</Card>}</div>}

export function StudentApp({user,onLogout}){const [tab,setTab]=useState("home");const [showNotif,setShowNotif]=useState(false);const [showMsg,setShowMsg]=useState(false);const student=lsG("students").find(s=>String(s.id)===String(user.ref));const tabs=[{key:"home",icon:"🏠",label:"Home"},{key:"timetable",icon:"📅",label:"Schedule"},{key:"materials",icon:"📚",label:"Materials"},{key:"homework",icon:"📝",label:"HW"},{key:"exams",icon:"📋",label:"Exams"},{key:"attendance",icon:"✅",label:"Attend."},{key:"marks",icon:"📊",label:"Marks"},{key:"fees",icon:"💰",label:"Fees"}];const content=tab==="home"?<STHome student={student}/>:tab==="timetable"?<STTimetable student={student}/>:tab==="materials"?<STMaterials/>:tab==="homework"?<STHomework student={student}/>:tab==="exams"?<STExamSchedule student={student}/>:tab==="attendance"?<STAttendance student={student}/>:tab==="marks"?<STMarks student={student}/>:<STFees student={student}/>;return <><Shell header={<AppBar name={user.name} role="student" userId={user.id} onLogout={onLogout} onNotif={()=>setShowNotif(true)} onMsg={()=>setShowMsg(true)}/>} tabs={tabs} activeTab={tab} setTab={setTab}>{content}</Shell>{showNotif&&<NotifPanel userId={user.id} onClose={()=>setShowNotif(false)}/>} {showMsg&&<MessagingPanel user={user} onClose={()=>setShowMsg(false)}/>}</>}
