import React,{useEffect,useState}from"react";
import {C,lsG}from"@/lg/data";
import {supabase}from"@/lg/supabase";
import {Badge,Card,Sec,Shell,AppBar}from"@/lg/ui";
import {NotifPanel}from"@/lg/panels";
import {STHome,STTimetable}from"@/lg/student";
const text=v=>v==null?"":String(v);
async function queryStudentData(student){
  if(!student)return {timetable:[],attendance:[],homework:[],fees:[],announcements:[],exams:[],folders:[],materials:[]};
  const sid=text(student.sid||student.id),cls=text(student.cls),sec=text(student.sec),batch=text(student.batch_id||student.batchId);
  const timetableQ=batch?supabase.from("timetable").select("id,cls,sec,subject,tid,day,slot,batchid,batchname").eq("batchid",batch).order("day").order("slot"):supabase.from("timetable").select("id,cls,sec,subject,tid,day,slot,batchid,batchname").eq("cls",cls).eq("sec",sec).order("day").order("slot");
  const homeworkQ=batch?supabase.from("homework").select("id,cls,sec,subject,desc,given,due,tid,completedby,pdfname,pdfdata,batch_id,created_at").eq("batch_id",batch).order("created_at",{ascending:false}):supabase.from("homework").select("id,cls,sec,subject,desc,given,due,tid,completedby,pdfname,pdfdata,batch_id,created_at").eq("cls",cls).eq("sec",sec).order("created_at",{ascending:false});
  const [tt,att,hw,fees,ann,exams,folders,materials]=await Promise.all([
    timetableQ,
    supabase.from("attendance").select("id,sid,date,status,by,created_at").eq("sid",sid).order("date",{ascending:false}),
    homeworkQ,
    supabase.from("fees").select("id,sid,desc,amount,due,status,paidon,created_at").eq("sid",sid).order("created_at",{ascending:false}),
    supabase.from("announcements").select("id,title,desc,date,target,created_at").in("target",["all",cls,sec,`${cls}-${sec}`]).order("created_at",{ascending:false}),
    supabase.from("examschedule").select("id,title,subject,cls,sec,date,starttime,endtime,venue,syllabus,totalmarks,createdby,startTime,endTime,totalMarks").eq("cls",cls).eq("sec",sec).order("date"),
    supabase.from("material_folders").select("id,name,parent_id,created_at").order("name"),
    supabase.from("materials").select("id,title,name,folder_id,batch_id,storage_path,file_size,mime_type,pdfdata,pdfname,desc,subject,created_at,cls,sec").order("created_at",{ascending:false})
  ]);
  const errors=[tt,att,hw,fees,ann,exams,folders,materials].filter(r=>r.error);
  if(errors.length)throw new Error(errors.map(r=>r.error.message).join("; "));
  const materialsData=(materials.data||[]).filter(m=>{const mb=text(m.batch_id),mc=text(m.cls),ms=text(m.sec);return(!mb||mb===batch)&&(!mc||mc===cls)&&(!ms||ms===sec)});
  return {timetable:tt.data||[],attendance:att.data||[],homework:hw.data||[],fees:fees.data||[],announcements:ann.data||[],exams:exams.data||[],folders:folders.data||[],materials:materialsData};
}
export function STAttendance({student}){const[rows,setRows]=useState([]),[error,setError]=useState("");useEffect(()=>{let live=true;(async()=>{try{setRows((await queryStudentData(student)).attendance)}catch(e){if(live)setError(e.message)}})();return()=>{live=false}},[student]);const present=rows.filter(a=>a.status==="present").length,absent=rows.filter(a=>a.status==="absent").length,leave=rows.filter(a=>a.status==="leave").length,rate=rows.length?Math.round(present/rows.length*100):0;return <div>{error&&<Card style={{color:C.red,marginBottom:10}}>{error}</Card>}<Card style={{textAlign:"center",padding:24,marginBottom:16}}><div style={{fontSize:34,fontWeight:900,color:rate>=75?C.green:C.red}}>{rate}%</div><div style={{fontSize:12,color:C.sub}}>Attendance</div><div style={{display:"flex",justifyContent:"center",gap:24,marginTop:16}}><div>✅ {present}</div><div>❌ {absent}</div><div>🟡 {leave}</div></div></Card><Sec title="Attendance Log 📋"/>{rows.length?rows.map(a=><Card key={a.id} style={{marginBottom:8,display:"flex",justifyContent:"space-between"}}><span>{a.date}</span><Badge label={a.status}/></Card>):<Card style={{textAlign:"center",padding:24,color:C.sub}}>No attendance records yet.</Card>}</div>}
export function STHomework({student}){const[rows,setRows]=useState([]),[error,setError]=useState("");useEffect(()=>{let live=true;(async()=>{try{setRows((await queryStudentData(student)).homework)}catch(e){if(live)setError(e.message)}})();return()=>{live=false}},[student]);return <div>{error&&<Card style={{color:C.red,marginBottom:10}}>{error}</Card>}<Sec title={`Homework (${rows.length}) 📝`}/>{rows.length?rows.map(h=><Card key={h.id} style={{marginBottom:10}}><Badge label={h.subject}/><span style={{fontSize:11,color:C.sub}}> Due: {h.due}</span><div style={{fontWeight:700,marginTop:8}}>{h.desc}</div>{h.pdfname&&<div style={{fontSize:11,color:C.sub,marginTop:6}}>Attachment: {h.pdfname}</div>}</Card>):<Card style={{textAlign:"center",padding:28,color:C.sub}}>No homework right now 🎉</Card>}</div>}
export function STMaterials({student}){const[folders,setFolders]=useState([]),[rows,setRows]=useState([]),[current,setCurrent]=useState(null),[error,setError]=useState(""),[loading,setLoading]=useState(true);useEffect(()=>{let live=true;(async()=>{setLoading(true);try{const d=await queryStudentData(student);if(live){setFolders(d.folders);setRows(d.materials)}}catch(e){if(live)setError(e.message)}finally{if(live)setLoading(false)}})();return()=>{live=false}},[student]);const visibleFolders=folders.filter(f=>f.parent_id===(current?.id??null)),visibleFiles=rows.filter(m=>m.folder_id===(current?.id??null));const download=async file=>{if(file.storage_path){const{data,error:e}=await supabase.storage.from("materials").download(file.storage_path);if(e){setError(e.message);return}const url=URL.createObjectURL(data),a=document.createElement("a");a.href=url;a.download=file.name||file.title||"material";document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);return}if(file.pdfdata){const a=document.createElement("a");a.href=file.pdfdata;a.download=file.pdfname||file.name||file.title||"material";document.body.appendChild(a);a.click();a.remove()}};return <div><Sec title="Study Materials 📚"/>{error&&<Card style={{color:C.red,marginBottom:10}}>{error}</Card>}{loading?<Card style={{textAlign:"center",padding:28,color:C.sub}}>Loading materials…</Card>:<>{visibleFolders.map(folder=><Card key={folder.id} onClick={()=>setCurrent(folder)} style={{marginBottom:10,cursor:"pointer",display:"flex",alignItems:"center",gap:12}}><div style={{fontSize:30}}>📁</div><div><div style={{fontWeight:900}}>{folder.name}</div><div style={{fontSize:11,color:C.sub}}>Open folder</div></div></Card>)}{visibleFiles.map(file=><Card key={file.id} style={{marginBottom:10}}><div style={{fontWeight:800}}>{file.title||file.name||"Material"}</div><div style={{fontSize:11,color:C.sub}}>{file.subject||""}</div><button onClick={()=>void download(file)} style={{marginTop:8,border:0,borderRadius:10,padding:"9px 12px",background:C.accent,color:"#fff",fontWeight:800}}>Download</button></Card>)}{!visibleFolders.length&&!visibleFiles.length&&<Card style={{textAlign:"center",padding:28,color:C.sub}}>{current?"This folder is empty.":"No study materials yet."}</Card>}</>}</div>}
export function STFees({student}){const[rows,setRows]=useState([]),[error,setError]=useState("");useEffect(()=>{let live=true;(async()=>{try{setRows((await queryStudentData(student)).fees)}catch(e){if(live)setError(e.message)}})();return()=>{live=false}},[student]);const total=rows.reduce((s,f)=>s+Number(f.amount||0),0),paid=rows.filter(f=>f.status==="paid").reduce((s,f)=>s+Number(f.amount||0),0);return <div>{error&&<Card style={{color:C.red,marginBottom:10}}>{error}</Card>}<Card style={{marginBottom:16}}><div style={{fontSize:12,color:C.sub}}>Total Fees</div><div style={{fontSize:26,fontWeight:900}}>₹{total.toLocaleString()}</div><div style={{fontSize:12,color:C.green}}>Paid ₹{paid.toLocaleString()} · Pending ₹{(total-paid).toLocaleString()}</div></Card><Sec title="Fee Records 💰"/>{rows.length?rows.map(f=><Card key={f.id} style={{marginBottom:9,display:"flex",justifyContent:"space-between"}}><div><div style={{fontWeight:700}}>{f.desc}</div><div style={{fontSize:11,color:C.sub}}>Due: {f.due}</div></div><div>₹{Number(f.amount||0).toLocaleString()}<div><Badge label={f.status}/></div></div></Card>):<Card style={{textAlign:"center",padding:24,color:C.sub}}>No fee records yet.</Card>}</div>}
export function STExamSchedule({student}){const[rows,setRows]=useState([]),[error,setError]=useState("");useEffect(()=>{let live=true;(async()=>{try{setRows((await queryStudentData(student)).exams)}catch(e){if(live)setError(e.message)}})();return()=>{live=false}},[student]);const today=new Date().toISOString().slice(0,10),upcoming=rows.filter(e=>text(e.date)>=today).sort((a,b)=>text(a.date).localeCompare(text(b.date)));return <div>{error&&<Card style={{color:C.red,marginBottom:10}}>{error}</Card>}<Sec title={`Upcoming Exams 📋 (${upcoming.length})`}/>{upcoming.length?upcoming.map(e=><Card key={e.id} style={{marginBottom:10}}><div style={{fontWeight:800}}>{e.title||e.subject}</div><div style={{fontSize:11,color:C.sub}}>{e.date} · {e.starttime||e.startTime||""}{(e.endtime||e.endTime)?`–${e.endtime||e.endTime}`:""}{e.venue?` · ${e.venue}`:""}</div></Card>):<Card style={{textAlign:"center",padding:28,color:C.sub}}>No upcoming exams.</Card>}</div>}
export function STAnnouncements({student}){const[rows,setRows]=useState([]),[error,setError]=useState("");useEffect(()=>{let live=true;(async()=>{try{setRows((await queryStudentData(student)).announcements)}catch(e){if(live)setError(e.message)}})();return()=>{live=false}},[student]);return <div>{error&&<Card style={{color:C.red,marginBottom:10}}>{error}</Card>}<Sec title="Announcements 📢"/>{rows.length?rows.map(a=><Card key={a.id} style={{marginBottom:10}}><div style={{fontWeight:800}}>{a.title}</div><div style={{fontSize:12,color:C.sub}}>{a.desc}</div><div style={{fontSize:10,color:C.sub,marginTop:5}}>{a.date||""}</div></Card>):<Card style={{textAlign:"center",padding:24,color:C.sub}}>No announcements.</Card>}</div>}
export function StudentApp({user,onLogout}){const[tab,setTab]=useState("home"),[showNotif,setShowNotif]=useState(false),[student,setStudent]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState("");useEffect(()=>{let live=true;(async()=>{try{const{data,error:e}=await supabase.from("students").select("id,name,sid,cls,sec,parentname,parentphone,parent,enroll,status,batch_id").eq("id",user.ref).maybeSingle();if(e)throw e;if(!data)throw new Error("Student profile could not be loaded");if(live)setStudent(data)}catch(e){if(live)setError(e.message)}finally{if(live)setLoading(false)}})();return()=>{live=false}},[user.ref]);const tabs=[{key:"home",icon:"🏠",label:"Home"},{key:"timetable",icon:"📅",label:"Schedule"},{key:"materials",icon:"📚",label:"Materials"},{key:"homework",icon:"📝",label:"HW"},{key:"exams",icon:"📋",label:"Exams"},{key:"attendance",icon:"✅",label:"Attend."},{key:"fees",icon:"💰",label:"Fees"}];const content=loading?<Card style={{textAlign:"center",padding:30,color:C.sub}}>Loading your student profile…</Card>:error?<Card style={{color:C.red,marginTop:20}}>{error}</Card>:tab==="home"?<STHome student={student}/>:tab==="timetable"?<STTimetable student={student}/>:tab==="materials"?<STMaterials student={student}/>:tab==="homework"?<STHomework student={student}/>:tab==="exams"?<STExamSchedule student={student}/>:tab==="attendance"?<STAttendance student={student}/>:<STFees student={student}/>;return <><Shell header={<AppBar name={user.name} role="student" userId={user.id} onLogout={onLogout} onNotif={()=>setShowNotif(true)}/>} tabs={tabs} activeTab={tab} setTab={setTab}>{content}</Shell>{showNotif&&<NotifPanel userId={user.id} onClose={()=>setShowNotif(false)}/>}</>}
