import React,{useEffect,useMemo,useState}from"react";
import {C,uid}from"@/lg/data";
import {supabase}from"@/lg/supabase";
import {Card,Badge,Sec,SBtn,GBtn,Shell,AppBar}from"@/lg/ui";
import {NotifPanel,MessagingPanel}from"@/lg/panels";
import {THHome,THSchedule,THAttendance}from"@/lg/teacher";
import {THMarks,THAnalytics}from"@/lg/marks";

const todayISO=()=>new Date().toISOString().slice(0,10);
const errText=e=>e instanceof Error?e.message:(e?.message||"Something went wrong. Please try again.");

async function loadTeacherBatches(teacherId){
  const {data:entries,error}=await supabase.from("timetable_entries").select("batch_id,subject_name").eq("teacher_id",teacherId).eq("status","active");
  if(error)throw error;
  const ids=[...new Set((entries||[]).map(x=>x.batch_id).filter(Boolean))];
  if(!ids.length)return[];
  const {data:batches,error:batchError}=await supabase.from("batches").select("id,name,cls,sec,status").in("id",ids);
  if(batchError)throw batchError;
  const subjects=new Map();
  for(const e of entries||[]){if(!subjects.has(String(e.batch_id)))subjects.set(String(e.batch_id),new Set());if(e.subject_name)subjects.get(String(e.batch_id)).add(e.subject_name)}
  return (batches||[]).filter(b=>b.status==null||b.status==="active").map(b=>({...b,subjects:[...(subjects.get(String(b.id))||new Set())]}));
}

export function T5Homework({teacher}){
  const [batches,setBatches]=useState([]),[rows,setRows]=useState([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[form,setForm]=useState({batchId:"",subject:"",desc:"",due:""});
  const refresh=async()=>{setLoading(true);setError("");try{const [bs,hw]=await Promise.all([loadTeacherBatches(teacher?.id),supabase.from("homework").select("*").eq("tid",teacher?.id).order("created_at",{ascending:false})]);if(hw.error)throw hw.error;setBatches(bs);setRows(hw.data||[]);setForm(f=>({...f,batchId:f.batchId||bs[0]?.id||"",subject:f.subject||bs[0]?.subjects?.[0]||""}));}catch(e){setError(errText(e))}finally{setLoading(false)}};
  useEffect(()=>{if(teacher?.id)void refresh()},[teacher?.id]);
  const selected=useMemo(()=>batches.find(b=>String(b.id)===String(form.batchId)),[batches,form.batchId]);
  const save=async()=>{if(!selected||!form.subject||!form.desc.trim()||!form.due){setError("Select a batch and subject, then enter homework and a due date.");return}if(!selected.subjects.includes(form.subject)){setError("That subject is not assigned to you for this batch.");return}setSaving(true);setError("");try{const payload={id:uid(),batch_id:selected.id,cls:selected.cls||"",sec:selected.sec||"",subject:form.subject,desc:form.desc.trim(),given:todayISO(),due:form.due,tid:teacher.id};const {error:e}=await supabase.from("homework").insert(payload);if(e)throw e;setForm(f=>({...f,desc:"",due:""}));await refresh()}catch(e){setError(errText(e))}finally{setSaving(false)}};
  const remove=async id=>{if(!window.confirm("Delete this homework?"))return;setError("");const {error:e}=await supabase.from("homework").delete().eq("id",id).eq("tid",teacher.id);if(e)setError(errText(e));else await refresh()};
  return <div><Sec title="Homework 📝"/><Card style={{marginBottom:14}}><div style={{fontWeight:800,color:C.text,marginBottom:10}}>Assign to my batch</div>{error&&<div style={{color:C.red,background:"#FFF1F2",padding:10,borderRadius:10,fontSize:12,marginBottom:10}}>{error}</div>}{loading?<div style={{color:C.sub,fontSize:13}}>Loading your batches…</div>:batches.length===0?<div style={{color:C.sub,fontSize:13}}>No active batches are assigned to you yet.</div>:<><select value={form.batchId} onChange={e=>{const b=batches.find(x=>String(x.id)===e.target.value);setForm(f=>({...f,batchId:e.target.value,subject:b?.subjects?.[0]||""}))}} style={{width:"100%",padding:11,borderRadius:10,border:`1px solid ${C.border}`,marginBottom:9}}>{batches.map(b=><option key={b.id} value={b.id}>{b.name} · Class {b.cls||"-"}-{b.sec||"-"}</option>)}</select><select value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})} style={{width:"100%",padding:11,borderRadius:10,border:`1px solid ${C.border}`,marginBottom:9}}>{selected?.subjects?.map(s=><option key={s}>{s}</option>)}</select><textarea value={form.desc} onChange={e=>setForm({...form,desc:e.target.value})} placeholder="Homework description" rows={3} style={{width:"100%",padding:11,borderRadius:10,border:`1px solid ${C.border}`,marginBottom:9,resize:"vertical"}}/><input type="date" value={form.due} onChange={e=>setForm({...form,due:e.target.value})} style={{width:"100%",padding:11,borderRadius:10,border:`1px solid ${C.border}`,marginBottom:10}}/><GBtn ch={saving?"Saving…":"Assign Homework ✓"} onClick={save} disabled={saving}/></>}</Card><Sec title={`My Homework (${rows.length})`}/>{rows.map(h=><Card key={h.id} style={{marginBottom:10}}><div style={{display:"flex",justifyContent:"space-between",gap:10}}><div><div style={{display:"flex",gap:7,alignItems:"center",marginBottom:5}}><Badge label={h.subject}/><span style={{fontSize:11,color:C.sub}}>{h.cls}-{h.sec}</span></div><div style={{fontWeight:700,color:C.text}}>{h.desc}</div><div style={{fontSize:11,color:C.sub,marginTop:5}}>Due: {h.due}</div></div><button onClick={()=>void remove(h.id)} style={{border:0,borderRadius:9,padding:"6px 9px",background:"#FFF1F2",color:C.red,cursor:"pointer"}}>🗑</button></div></Card>)}{!loading&&!rows.length&&<Card style={{textAlign:"center",padding:24,color:C.sub,fontSize:13}}>No homework assigned yet.</Card>}</div>;
}

export function T6Materials({teacher}){
  const [batches,setBatches]=useState([]),[rows,setRows]=useState([]),[loading,setLoading]=useState(true),[uploading,setUploading]=useState(false),[error,setError]=useState("");
  const [form,setForm]=useState({batchId:"",subject:"",title:"",desc:""});
  const refresh=async()=>{setLoading(true);setError("");try{const [bs,m]=await Promise.all([loadTeacherBatches(teacher?.id),supabase.from("materials").select("id,batch_id,cls,sec,subject,title,desc,date,tid,storage_path,file_size,mime_type,name").eq("tid",teacher?.id).order("created_at",{ascending:false})]);if(m.error)throw m.error;setBatches(bs);setRows(m.data||[]);setForm(f=>({...f,batchId:f.batchId||bs[0]?.id||"",subject:f.subject||bs[0]?.subjects?.[0]||""}))}catch(e){setError(errText(e))}finally{setLoading(false)}};
  useEffect(()=>{if(teacher?.id)void refresh()},[teacher?.id]);
  const selected=useMemo(()=>batches.find(b=>String(b.id)===String(form.batchId)),[batches,form.batchId]);
  const download=async row=>{setError("");if(!row.storage_path){setError("This material has no downloadable storage file.");return}const {data,e}=await supabase.storage.from("materials").createSignedUrl(row.storage_path,3600,{download:row.name||row.title||"material"});if(e){setError(errText(e));return}window.open(data.signedUrl,"_blank","noopener,noreferrer")};
  const upload=async file=>{if(!selected||!form.subject||!form.title.trim()){setError("Select a batch and subject and enter a title first.");return}if(!file){return}if(file.size>50*1024*1024){setError("Maximum file size is 50 MB.");return}setUploading(true);setError("");const path=`teacher/${teacher.id}/${selected.id}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"_")}`;try{const {error:up}=await supabase.storage.from("materials").upload(path,file,{upsert:false,contentType:file.type||"application/octet-stream"});if(up)throw up;const payload={id:uid(),batch_id:selected.id,cls:selected.cls||null,sec:selected.sec||null,subject:form.subject,title:form.title.trim(),desc:form.desc.trim()||null,date:todayISO(),tid:teacher.id,storage_path:path,file_size:file.size,mime_type:file.type||null,name:file.name};const {error:ins}=await supabase.from("materials").insert(payload);if(ins){await supabase.storage.from("materials").remove([path]);throw ins}setForm(f=>({...f,title:"",desc:""}));await refresh()}catch(e){setError(errText(e))}finally{setUploading(false)}};
  const remove=async row=>{if(!window.confirm("Delete this material?"))return;setError("");const {error:e}=await supabase.from("materials").delete().eq("id",row.id).eq("tid",teacher.id);if(e){setError(errText(e));return}if(row.storage_path)await supabase.storage.from("materials").remove([row.storage_path]);await refresh()};
  return <div><Sec title="Study Materials 📚"/><Card style={{marginBottom:14}}><div style={{fontWeight:800,color:C.text,marginBottom:10}}>Add material to my batch</div>{error&&<div style={{color:C.red,background:"#FFF1F2",padding:10,borderRadius:10,fontSize:12,marginBottom:10}}>{error}</div>}{loading?<div style={{color:C.sub,fontSize:13}}>Loading your batches…</div>:batches.length===0?<div style={{color:C.sub,fontSize:13}}>No active batches are assigned to you yet.</div>:<><select value={form.batchId} onChange={e=>{const b=batches.find(x=>String(x.id)===e.target.value);setForm(f=>({...f,batchId:e.target.value,subject:b?.subjects?.[0]||""}))}} style={{width:"100%",padding:11,borderRadius:10,border:`1px solid ${C.border}`,marginBottom:9}}>{batches.map(b=><option key={b.id} value={b.id}>{b.name} · Class {b.cls||"-"}-{b.sec||"-"}</option>)}</select><select value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})} style={{width:"100%",padding:11,borderRadius:10,border:`1px solid ${C.border}`,marginBottom:9}}>{selected?.subjects?.map(s=><option key={s}>{s}</option>)}</select><input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Material title" style={{width:"100%",padding:11,borderRadius:10,border:`1px solid ${C.border}`,marginBottom:9}}/><input value={form.desc} onChange={e=>setForm({...form,desc:e.target.value})} placeholder="Description (optional)" style={{width:"100%",padding:11,borderRadius:10,border:`1px solid ${C.border}`,marginBottom:9}}/><input type="file" accept="application/pdf,.pdf" disabled={uploading} onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f);e.target.value=""}} style={{width:"100%",padding:8,borderRadius:10,border:`1px dashed ${C.border}`}}/><div style={{fontSize:11,color:C.sub,marginTop:6}}>{uploading?"Uploading…":"PDF only · maximum 50 MB"}</div></>}</Card><Sec title={`My Materials (${rows.length})`}/>{rows.map(m=><Card key={m.id} style={{marginBottom:10}}><div style={{display:"flex",justifyContent:"space-between",gap:10}}><div><div style={{display:"flex",gap:7,alignItems:"center",marginBottom:5}}><Badge label={m.subject||"Material"}/><span style={{fontSize:11,color:C.sub}}>{m.cls||"-"}-{m.sec||"-"}</span></div><div style={{fontWeight:700,color:C.text}}>{m.title}</div><div style={{fontSize:11,color:C.sub,marginTop:4}}>{m.name||"PDF"} · {m.file_size?Math.ceil(m.file_size/1024):0} KB</div></div><div style={{display:"flex",gap:6}}><button onClick={()=>void download(m)} style={{border:0,borderRadius:9,padding:"6px 9px",background:"#EEF2FF",color:C.accent,cursor:"pointer"}}>↓</button><button onClick={()=>void remove(m)} style={{border:0,borderRadius:9,padding:"6px 9px",background:"#FFF1F2",color:C.red,cursor:"pointer"}}>🗑</button></div></div></Card>)}{!loading&&!rows.length&&<Card style={{textAlign:"center",padding:24,color:C.sub,fontSize:13}}>No materials yet.</Card>}</div>;
}

export function TeacherApp({user,onLogout}){
 const [tab,setTab]=useState("home"),[showNotif,setShowNotif]=useState(false),[showMsg,setShowMsg]=useState(false);
 const teacher={id:user.ref,name:user.name,subject:"",classes:[]};
 const tabs=[{key:"home",icon:"🏠",label:"Home"},{key:"schedule",icon:"📅",label:"Schedule"},{key:"attendance",icon:"✅",label:"Attend."},{key:"homework",icon:"📝",label:"HW"},{key:"materials",icon:"📚",label:"Notes"},{key:"marks",icon:"📊",label:"Marks"},{key:"analytics",icon:"📈",label:"Analytics"}];
 const content=tab==="home"?<THHome teacher={teacher}/>:tab==="schedule"?<THSchedule teacher={teacher}/>:tab==="attendance"?<THAttendance teacher={teacher}/>:tab==="homework"?<T5Homework teacher={teacher}/>:tab==="materials"?<T6Materials teacher={teacher}/>:tab==="marks"?<THMarks teacher={teacher}/>:<THAnalytics teacher={teacher}/>;
 return <><Shell header={<AppBar name={user.name} role="teacher" userId={user.id} onLogout={onLogout} onNotif={()=>setShowNotif(true)} onMsg={()=>setShowMsg(true)}/>} tabs={tabs} activeTab={tab} setTab={setTab}>{content}</Shell>{showNotif&&<NotifPanel userId={user.id} onClose={()=>setShowNotif(false)}/>} {showMsg&&<MessagingPanel user={user} onClose={()=>setShowMsg(false)}/>}</>;
}
